#ifndef BOAROS_RISCV_VIRTIO_MMIO_NET_H
#define BOAROS_RISCV_VIRTIO_MMIO_NET_H
#include <kernel/virtio_net.h>
#define riscv_virtio_mmio_net virtio_net_device
#define riscv_net_frame virtio_net_frame
#define riscv_net_tx_segment virtio_net_tx_segment
#define riscv_net_statistics virtio_net_statistics
#define RISCV_NET_QUEUE_SIZE VIRTIO_NET_QUEUE_SIZE
#define RISCV_NET_BUFFERS VIRTIO_NET_BUFFERS
#define RISCV_NET_BUFFER_SIZE VIRTIO_NET_BUFFER_SIZE
#define RISCV_NET_TX_SEGMENTS VIRTIO_NET_TX_SEGMENTS
#define RISCV_NET_TX_TABLE_OFFSET VIRTIO_NET_TX_TABLE_OFFSET
int riscv_virtio_mmio_net_init(struct virtio_net_device *,volatile void *,uint64_t,
    struct physical_page_allocator *,uint64_t,uint32_t);
#define riscv_virtio_mmio_net_stop virtio_net_stop
#define riscv_virtio_mmio_net_service virtio_net_service
#define riscv_virtio_mmio_net_receive virtio_net_receive
#define riscv_virtio_mmio_net_lend virtio_net_lend
#define riscv_virtio_mmio_net_release virtio_net_release
#define riscv_virtio_mmio_net_send virtio_net_send
#define riscv_virtio_mmio_net_send_copy virtio_net_send_copy
#define riscv_virtio_mmio_net_send_segments virtio_net_send_segments
#define riscv_virtio_mmio_net_tx_release virtio_net_tx_release
#endif
