#ifndef BOAROS_KERNEL_ERRNO_H
#define BOAROS_KERNEL_ERRNO_H

#define KERNEL_EPERM 1
#define KERNEL_ENOENT 2
#define KERNEL_ESRCH 3
#define KERNEL_EINTR 4
#define KERNEL_EIO 5
#define KERNEL_ENXIO 6
#define KERNEL_E2BIG 7
#define KERNEL_ENOEXEC 8
#define KERNEL_EBADF 9
#define KERNEL_ECHILD 10
#define KERNEL_EAGAIN 11
#define KERNEL_ENOMEM 12
#define KERNEL_EACCES 13
#define KERNEL_EFAULT 14
#define KERNEL_ENOTBLK 15
#define KERNEL_EBUSY 16
#define KERNEL_EEXIST 17
#define KERNEL_EXDEV 18
#define KERNEL_ENODEV 19
#define KERNEL_ENOTDIR 20
#define KERNEL_EISDIR 21
#define KERNEL_EINVAL 22
#define KERNEL_EMFILE 24
#define KERNEL_ENOTTY 25
#define KERNEL_ETXTBSY 26
#define KERNEL_EFBIG 27
#define KERNEL_ENOSPC 28
#define KERNEL_ESPIPE 29
#define KERNEL_EPIPE 32
#define KERNEL_EMLINK 31
#define KERNEL_EROFS 30
#define KERNEL_ERANGE 34
#define KERNEL_EDEADLK 35
#define KERNEL_ENAMETOOLONG 36
#define KERNEL_ENOLCK 37
#define KERNEL_ENOSYS 38
#define KERNEL_ENOTEMPTY 39
#define KERNEL_ELOOP 40
#define KERNEL_EMSGSIZE 90
#define KERNEL_EOPNOTSUPP 95
#define KERNEL_EADDRINUSE 98
#define KERNEL_ENETUNREACH 101
#define KERNEL_ECONNABORTED 103
#define KERNEL_ECONNRESET 104
#define KERNEL_EISCONN 106
#define KERNEL_ENOTCONN 107
#define KERNEL_EALREADY 114
#define KERNEL_EINPROGRESS 115
#define KERNEL_ENODATA 61
#define KERNEL_EOVERFLOW 75
#define KERNEL_ELIBBAD 80
#define KERNEL_ENOTSOCK 88
#define KERNEL_EDESTADDRREQ 89
#define KERNEL_ESOCKTNOSUPPORT 94
#define KERNEL_EPROTONOSUPPORT 93
#define KERNEL_ENOTSUP 95
#define KERNEL_EAFNOSUPPORT 97
#define KERNEL_EIDRM 43
#define KERNEL_ETIMEDOUT 110
#define KERNEL_EUCLEAN 117

/* Internal scheduler result; never exposed as a Linux errno. */
#define KERNEL_ERESTARTSYS 512

#endif
