#ifndef BOAROS_KERNEL_ERRNO_H
#define BOAROS_KERNEL_ERRNO_H

#define KERNEL_EPERM 1
#define KERNEL_ENOENT 2
#define KERNEL_ESRCH 3
#define KERNEL_EINTR 4
#define KERNEL_EIO 5
#define KERNEL_ENXIO 6
#define KERNEL_E2BIG 7
#define KERNEL_ENOEXEC 8
#define KERNEL_EBADF 9
#define KERNEL_ECHILD 10
#define KERNEL_EAGAIN 11
#define KERNEL_ENOMEM 12
#define KERNEL_EACCES 13
#define KERNEL_EFAULT 14
#define KERNEL_EBUSY 16
#define KERNEL_EEXIST 17
#define KERNEL_ENODEV 19
#define KERNEL_ENOTDIR 20
#define KERNEL_EISDIR 21
#define KERNEL_EINVAL 22
#define KERNEL_EMFILE 24
#define KERNEL_EFBIG 27
#define KERNEL_ENOSPC 28
#define KERNEL_ESPIPE 29
#define KERNEL_EPIPE 32
#define KERNEL_EROFS 30
#define KERNEL_ERANGE 34
#define KERNEL_ENAMETOOLONG 36
#define KERNEL_ENOSYS 38
#define KERNEL_ENOTEMPTY 39
#define KERNEL_ENODATA 61
#define KERNEL_EOVERFLOW 75
#define KERNEL_ELIBBAD 80
#define KERNEL_ENOTSUP 95
#define KERNEL_EUCLEAN 117

/* Internal scheduler result; never exposed as a Linux errno. */
#define KERNEL_ERESTARTSYS 512

#endif
